import type { Stop, BusRoute, Bus } from '@/types';

// Data derived from the user-provided CSV

export const stops: Stop[] = [
  { id: 'bajal', name: 'Bajal', position: { lat: 10, lng: 10 } },
  { id: 'statebank', name: 'Statebank', position: { lat: 10, lng: 20 } },
  { id: 'thandolige', name: 'Thandolige', position: { lat: 10, lng: 30 } },
  { id: 'muger', name: 'Muger', position: { lat: 10, lng: 40 } },
  { id: 'yekkur', name: 'Yekkur', position: { lat: 20, lng: 40 } },
  { id: 'pompwell', name: 'Pompwell', position: { lat: 20, lng: 30 } },
  { id: 'kankanady', name: 'Kankanady', position: { lat: 20, lng: 20 } },
  { id: 'jyothi', name: 'Jyothi', position: { lat: 20, lng: 10 } },
  { id: 'milagres', name: 'Milagres', position: { lat: 30, lng: 10 } },
  { id: 'railway-station', name: 'Railway Station', position: { lat: 30, lng: 20 } },
  { id: 'adyar', name: 'Adyar', position: { lat: 40, lng: 20 } },
  { id: 'signal', name: 'Signal', position: { lat: 40, lng: 30 } },
  { id: 'falnir', name: 'Falnir', position: { lat: 30, lng: 30 } },
  { id: 'inland-hospi', name: 'Inland Hospital', position: { lat: 30, lng: 40 } },
  { id: 'padil', name: 'Padil', position: { lat: 40, lng: 40 } },
  { id: 'kannur', name: 'Kannur', position: { lat: 50, lng: 40 } },
  { id: 'adyar-katte', name: 'Adyar Katte', position: { lat: 50, lng: 30 } },
  { id: 'puttur', name: 'Puttur', position: { lat: 60, lng: 20 } },
  { id: 'valachil', name: 'Valachil', position: { lat: 60, lng: 30 } },
  { id: 'thumbe', name: 'Thumbe', position: { lat: 60, lng: 40 } },
  { id: 'parangipete-bc-road', name: 'Parangipete BC Road', position: { lat: 70, lng: 40 } },
  { id: 'kalladka', name: 'Kalladka', position: { lat: 70, lng: 30 } },
  { id: 'mani', name: 'Mani', position: { lat: 70, lng: 20 } },
  { id: 'kabaka', name: 'Kabaka', position: { lat: 70, lng: 10 } },
  { id: 'perne', name: 'Perne', position: { lat: 80, lng: 20 } },
  { id: 'uppinangad', name: 'Uppinangad', position: { lat: 80, lng: 30 } },
  { id: 'talapady', name: 'Talapady', position: { lat: 15, lng: 5 } },
  { id: 'ekkur', name: 'Ekkur', position: { lat: 25, lng: 15 } },
  { id: 'kallapu', name: 'Kallapu', position: { lat: 35, lng: 5 } },
  { id: 'thokuttu', name: 'Thokuttu', position: { lat: 35, lng: 15 } },
  { id: 'kapikad', name: 'Kapikad', position: { lat: 35, lng: 25 } },
  { id: 'kumpala', name: 'Kumpala', position: { lat: 35, lng: 35 } },
  { id: 'someshwar', name: 'Someshwar', position: { lat: 45, lng: 35 } },
  { id: 'ullala', name: 'Ullala', position: { lat: 25, lng: 5 } },
  { id: 'overbridge', name: 'Overbridge', position: { lat: 45, lng: 15 } },
  { id: 'abakka-circ', name: 'Abakka Circle', position: { lat: 45, lng: 25 } },
  { id: 'surathkal', name: 'Surathkal', position: { lat: 55, lng: 15 } },
  { id: 'polali', name: 'Polali', position: { lat: 55, lng: 25 } },
  { id: 'kaikamba', name: 'Kaikamba', position: { lat: 55, lng: 35 } },
  { id: 'bajpe', name: 'Bajpe', position: { lat: 55, lng: 45 } },
  { id: 'mulki', name: 'Mulki', position: { lat: 65, lng: 45 } },
  { id: 'kateel', name: 'Kateel', position: { lat: 65, lng: 15 } },
];

export const routes: BusRoute[] = [
  { id: 'route_9A', name: '9A Bajal -> Statebank', stops: ['bajal', 'thandolige', 'muger', 'yekkur', 'pompwell', 'kankanady', 'jyothi', 'milagres', 'railway-station', 'statebank'] },
  { id: 'route_9B', name: '9B Statebank -> Bajal', stops: [ 'statebank', 'railway-station', 'milagres', 'jyothi', 'kankanady', 'pompwell', 'yekkur', 'muger', 'thandolige', 'bajal'] },
  { id: 'route_11A_Rajkumar', name: '11A Statebank -> Adyar', stops: ['statebank', 'jyothi', 'kankanady', 'pompwell', 'inland-hospi', 'falnir', 'signal', 'milagres', 'railway-station', 'adyar-katte', 'kannur', 'padil', 'adyar'] },
  { id: 'route_11A_SK', name: '11A Adyar -> Statebank', stops: ['adyar', 'padil', 'kannur', 'adyar-katte', 'railway-station', 'milagres', 'signal', 'falnir', 'inland-hospi', 'pompwell', 'kankanady', 'jyothi', 'statebank' ] },
  { id: 'route_Mahesh', name: 'Mahesh Statebank -> Puttur', stops: ['statebank', 'signal', 'jyothi', 'kankanady', 'pompwell', 'padil', 'kannur', 'adyar', 'valachil', 'thumbe', 'parangipete-bc-road', 'kalladka', 'mani', 'kabaka', 'puttur'] },
  { id: 'route_Celina', name: 'Celina Statebank -> Puttur', stops: ['statebank', 'signal', 'jyothi', 'kankanady', 'pompwell', 'padil', 'kannur', 'adyar', 'valachil', 'thumbe', 'parangipete-bc-road', 'kalladka', 'mani', 'perne', 'uppinangad', 'puttur'] },
  { id: 'route_42', name: '42 Statebank -> Talapady', stops: ['statebank', 'signal', 'jyothi', 'kankanady', 'pompwell', 'ekkur', 'muger', 'kallapu', 'thokuttu', 'kapikad', 'kumpala', 'someshwar', 'talapady'] },
  { id: 'route_44', name: '44 Statebank -> Ullala', stops: ['statebank', 'signal', 'jyothi', 'kankanady', 'pompwell', 'ekkur', 'muger', 'kallapu', 'thokuttu', 'overbridge', 'abakka-circ', 'someshwar', 'ullala'] },
  { id: 'route_15A', name: '15A Statebank -> Surathkal', stops: ['statebank', 'jyothi', 'kankanady', 'pompwell', 'padil', 'kannur', 'polali', 'kaikamba', 'bajpe', 'mulki', 'surathkal'] },
  { id: 'route_16A', name: '16A Statebank -> Kateel', stops: ['statebank', 'signal', 'milagres', 'falnir', 'kankanady', 'padil', 'kannur', 'polali', 'kateel'] },
];

export const initialBuses: Bus[] = [
  { id: 'bus_9A_1', routeId: 'route_9A', currentStopIndex: 1, progress: 0.3, speed: 0.1, position: { lat: 10, lng: 23 }, name: 'Kusuma' },
  { id: 'bus_9B_1', routeId: 'route_9B', currentStopIndex: 4, progress: 0.8, speed: 0.1, position: { lat: 18, lng: 40 }, name: 'Kusuma' },
  { id: 'bus_11A_R_1', routeId: 'route_11A_Rajkumar', currentStopIndex: 2, progress: 0.1, speed: 0.09, position: { lat: 40, lng: 31 }, name: 'Rajkumar' },
  { id: 'bus_11A_SK_1', routeId: 'route_11A_SK', currentStopIndex: 5, progress: 0.5, speed: 0.09, position: { lat: 30, lng: 30 }, name: 'SK Travels' },
  { id: 'bus_Mahesh_1', routeId: 'route_Mahesh', currentStopIndex: 7, progress: 0.2, speed: 0.08, position: { lat: 50, lng: 40 }, name: 'Mahesh' },
  { id: 'bus_Celina_1', routeId: 'route_Celina', currentStopIndex: 10, progress: 0.9, speed: 0.08, position: { lat: 60, lng: 40 }, name: 'Celina' },
  { id: 'bus_42_1', routeId: 'route_42', currentStopIndex: 6, progress: 0.4, speed: 0.1, position: { lat: 25, lng: 15 }, name: 'Praise the Lord' },
  { id: 'bus_44_1', routeId: 'route_44', currentStopIndex: 3, progress: 0.7, speed: 0.1, position: { lat: 20, lng: 10 }, name: 'Celina' },
  { id: 'bus_15A_1', routeId: 'route_15A', currentStopIndex: 8, progress: 0.6, speed: 0.09, position: { lat: 55, lng: 35 }, name: 'Durgamba' },
  { id: 'bus_16A_1', routeId: 'route_16A', currentStopIndex: 4, progress: 0.2, speed: 0.09, position: { lat: 30, lng: 30 }, name: 'Rajahams' },
];
